const nouns = [
    { word: "apple", article: "an" },
    { word: "banana" },
    { word: "box", plural: "boxes" },
    { word: "cactus", plural: "cacti" },
    { word: "child", plural: "children" },
    { word: "city", plural: "cities" },
    { word: "deer", plural: "deer" },
    { word: "dog" },
    { word: "elephant", article: "an" },
    { word: "elf", plural: "elves" },
    { word: "ferry", plural: "ferries" },
    { word: "fish", plural: "fish" },
    { word: "fox", plural: "foxes" },
    { word: "goose", plural: "geese" },
    { word: "half", plural: "halves" },
    { word: "hero", plural: "heroes" },
    { word: "house" },
    { word: "idea" },
    { word: "jungle" },
    { word: "knife", plural: "knives" },
    { word: "lady", plural: "ladies" },
    { word: "leaf", plural: "leaves" },
    { word: "loaf", plural: "loaves" },
    { word: "man", plural: "men" },
    { word: "moose", plural: "moose" },
    { word: "mouse", plural: "mice" },
    { word: "notebook" },
    { word: "orange", article: "an" },
    { word: "penny", plural: "pennies" },
    { word: "person", plural: "people" },
    { word: "piano", plural: "pianos" },
    { word: "potato", plural: "potatoes" },
    { word: "quiz", plural: "quizzes" },
    { word: "rabbit" },
    { word: "radio", plural: "radios" },
    { word: "shark" },
    { word: "sheep", plural: "sheep" },
    { word: "sky", plural: "skies" },
    { word: "song" },
    { word: "tooth", plural: "teeth" },
    { word: "tornado", plural: "tornadoes" },
    { word: "umbrella", article: "an" },
    { word: "valley" },
    { word: "volcano", plural: "volcanoes" },
    { word: "watch", plural: "watches" },
    { word: "wolf", plural: "wolves" },
    { word: "woman", plural: "women" },
    { word: "xylophone" },
    { word: "yacht" },
    { word: "zoo" }
];

const adjectives = [
    { word: "angry", article: "an" },
    { word: "beautiful", article: "a" },
    { word: "bright", article: "a" },
    { word: "brave", article: "a" },
    { word: "calm", article: "a" },
    { word: "clever", article: "a" },
    { word: "dangerous", article: "a" },
    { word: "elegant", article: "an" },
    { word: "fancy", article: "a" },
    { word: "fierce", article: "a" },
    { word: "friendly", article: "a" },
    { word: "grumpy", article: "a" },
    { word: "happy", article: "a" },
    { word: "honest", article: "an" },
    { word: "icy", article: "an" },
    { word: "innocent", article: "an" },
    { word: "intelligent", article: "an" },
    { word: "jolly", article: "a" },
    { word: "kind", article: "a" },
    { word: "kindhearted", article: "a" },
    { word: "lazy", article: "a" },
    { word: "loud", article: "a" },
    { word: "mighty", article: "a" },
    { word: "mysterious", article: "a" },
    { word: "nervous", article: "a" },
    { word: "noble", article: "a" },
    { word: "obedient", article: "an" },
    { word: "old", article: "an" },
    { word: "powerful", article: "a" },
    { word: "quick", article: "a" },
    { word: "quiet", article: "a" },
    { word: "rare", article: "a" },
    { word: "rugged", article: "a" },
    { word: "shiny", article: "a" },
    { word: "silly", article: "a" },
    { word: "strong", article: "a" },
    { word: "tall", article: "a" },
    { word: "trustworthy", article: "a" },
    { word: "ugly", article: "an" },
    { word: "unique", article: "a" },
    { word: "vibrant", article: "a" },
    { word: "wild", article: "a" },
    { word: "witty", article: "a" },
    { word: "xenial", article: "a" },
    { word: "yearly", article: "a" },
    { word: "young", article: "a" },
    { word: "zany", article: "a" },
    { word: "zealous", article: "a" }
];

const verbs = [
    { base: "accept", past: "accepted", pastParticiple: "accepted", continuous: "accepting" },
    { base: "admire", past: "admired", pastParticiple: "admired", continuous: "admiring" },
    { base: "advise", past: "advised", pastParticiple: "advised", continuous: "advising" },
    { base: "answer", past: "answered", pastParticiple: "answered", continuous: "answering" },
    { base: "ask", past: "asked", pastParticiple: "asked", continuous: "asking" },
    { base: "build", past: "built", pastParticiple: "built", continuous: "building" },
    { base: "buy", past: "bought", pastParticiple: "bought", continuous: "buying" },
    { base: "call", past: "called", pastParticiple: "called", continuous: "calling" },
    { base: "catch", past: "caught", pastParticiple: "caught", continuous: "catching" },
    { base: "choose", past: "chose", pastParticiple: "chosen", continuous: "choosing" },
    { base: "clean", past: "cleaned", pastParticiple: "cleaned", continuous: "cleaning" },
    { base: "close", past: "closed", pastParticiple: "closed", continuous: "closing" },
    { base: "collect", past: "collected", pastParticiple: "collected", continuous: "collecting" },
    { base: "compare", past: "compared", pastParticiple: "compared", continuous: "comparing" },
    { base: "complete", past: "completed", pastParticiple: "completed", continuous: "completing" },
    { base: "create", past: "created", pastParticiple: "created", continuous: "creating" },
    { base: "deliver", past: "delivered", pastParticiple: "delivered", continuous: "delivering" },
    { base: "design", past: "designed", pastParticiple: "designed", continuous: "designing" },
    { base: "discover", past: "discovered", pastParticiple: "discovered", continuous: "discovering" },
    { base: "divide", past: "divided", pastParticiple: "divided", continuous: "dividing" },
    { base: "enjoy", past: "enjoyed", pastParticiple: "enjoyed", continuous: "enjoying" },
    { base: "explain", past: "explained", pastParticiple: "explained", continuous: "explaining" },
    { base: "fix", past: "fixed", pastParticiple: "fixed", continuous: "fixing" },
    { base: "follow", past: "followed", pastParticiple: "followed", continuous: "following" },
    { base: "handle", past: "handled", pastParticiple: "handled", continuous: "handling" },
    { base: "help", past: "helped", pastParticiple: "helped", continuous: "helping" },
    { base: "hold", past: "held", pastParticiple: "held", continuous: "holding" },
    { base: "include", past: "included", pastParticiple: "included", continuous: "including" },
    { base: "invite", past: "invited", pastParticiple: "invited", continuous: "inviting" },
    { base: "join", past: "joined", pastParticiple: "joined", continuous: "joining" },
    { base: "know", past: "knew", pastParticiple: "known", continuous: "knowing" },
    { base: "learn", past: "learned", pastParticiple: "learned", continuous: "learning" },
    { base: "like", past: "liked", pastParticiple: "liked", continuous: "liking" },
    { base: "make", past: "made", pastParticiple: "made", continuous: "making" },
    { base: "meet", past: "met", pastParticiple: "met", continuous: "meeting" },
    { base: "offer", past: "offered", pastParticiple: "offered", continuous: "offering" },
    { base: "open", past: "opened", pastParticiple: "opened", continuous: "opening" },
    { base: "paint", past: "painted", pastParticiple: "painted", continuous: "painting" },
    { base: "plan", past: "planned", pastParticiple: "planned", continuous: "planning" },
    { base: "play", past: "played", pastParticiple: "played", continuous: "playing" },
    { base: "prepare", past: "prepared", pastParticiple: "prepared", continuous: "preparing" },
    { base: "reach", past: "reached", pastParticiple: "reached", continuous: "reaching" },
    { base: "read", past: "read", pastParticiple: "read", continuous: "reading" },
    { base: "repair", past: "repaired", pastParticiple: "repaired", continuous: "repairing" },
    { base: "sell", past: "sold", pastParticiple: "sold", continuous: "selling" },
    { base: "send", past: "sent", pastParticiple: "sent", continuous: "sending" },
    { base: "show", past: "showed", pastParticiple: "shown", continuous: "showing" },
    { base: "start", past: "started", pastParticiple: "started", continuous: "starting" },
    { base: "take", past: "took", pastParticiple: "taken", continuous: "taking" },
    { base: "teach", past: "taught", pastParticiple: "taught", continuous: "teaching" },
    { base: "write", past: "wrote", pastParticiple: "written", continuous: "writing" }
  ];

const tenses = [
    { tense: "Present Simple", template: "{Subject} {Verb}s {Object}.", form: "base" },
    { tense: "Present Continuous", template: "{Subject} <is/are> {Verb} {Object}.", form: "continuous" },
    { tense: "Present Perfect", template: "{Subject} <has/have> {Verb} {Object}.", form: "pastParticiple" },
    { tense: "Present Perfect Continuous", template: "{Subject} <has/have> been {Verb} {Object}.", form: "continuous" },
    { tense: "Past Simple", template: "{Subject} {Verb} {Object}.", form: "past" },
    { tense: "Past Continuous", template: "{Subject} <was/were> {Verb} {Object}.", form: "continuous" },
    { tense: "Past Perfect", template: "{Subject} had {Verb} {Object}.", form: "pastParticiple" },
    { tense: "Past Perfect Continuous", template: "{Subject} had been {Verb} {Object}.", form: "continuous" },
    { tense: "Future Simple", template: "{Subject} will {Verb} {Object}.", form: "base" },
    { tense: "Future Continuous", template: "{Subject} will be {Verb} {Object}.", form: "continuous" },
    { tense: "Future Perfect", template: "{Subject} will have {Verb} {Object}.", form: "pastParticiple" },
    { tense: "Future Perfect Continuous", template: "{Subject} will have been {Verb} {Object}.", form: "continuous" },
];