const nouns = [
    { word: "apple", article: "an" },
    { word: "banana" },
    { word: "box", plural: "boxes" },
    { word: "cactus", plural: "cacti" },
    { word: "child", plural: "children" },
    { word: "city", plural: "cities" },
    { word: "deer", plural: "deer" },
    { word: "dog" },
    { word: "elephant", article: "an" },
    { word: "elf", plural: "elves" },
    { word: "ferry", plural: "ferries" },
    { word: "fish", plural: "fish" },
    { word: "fox", plural: "foxes" },
    { word: "goose", plural: "geese" },
    { word: "half", plural: "halves" },
    { word: "hero", plural: "heroes" },
    { word: "house" },
    { word: "idea" },
    { word: "jungle" },
    { word: "knife", plural: "knives" },
    { word: "lady", plural: "ladies" },
    { word: "leaf", plural: "leaves" },
    { word: "loaf", plural: "loaves" },
    { word: "man", plural: "men" },
    { word: "moose", plural: "moose" },
    { word: "mouse", plural: "mice" },
    { word: "notebook" },
    { word: "orange", article: "an" },
    { word: "penny", plural: "pennies" },
    { word: "person", plural: "people" },
    { word: "piano", plural: "pianos" },
    { word: "potato", plural: "potatoes" },
    { word: "quiz", plural: "quizzes" },
    { word: "rabbit" },
    { word: "radio", plural: "radios" },
    { word: "shark" },
    { word: "sheep", plural: "sheep" },
    { word: "sky", plural: "skies" },
    { word: "song" },
    { word: "tooth", plural: "teeth" },
    { word: "tornado", plural: "tornadoes" },
    { word: "umbrella", article: "an" },
    { word: "valley" },
    { word: "volcano", plural: "volcanoes" },
    { word: "watch", plural: "watches" },
    { word: "wolf", plural: "wolves" },
    { word: "woman", plural: "women" },
    { word: "xylophone" },
    { word: "yacht" },
    { word: "zoo" }
];

const adjectives = [
    "Angry",
    "Beautiful",
    "Brave",
    "Calm",
    "Clever",
    "Dangerous",
    "Elegant",
    "Fancy",
    "Fierce",
    "Friendly",
    "Grumpy",
    "Happy",
    "Honest",
    "Innocent",
    "Intelligent",
    "Jolly",
    "Kind",
    "Kindhearted",
    "Lazy",
    "Loud",
    "Mighty",
    "Mysterious",
    "Nervous",
    "Noble",
    "Obedient",
    "Powerful",
    "Quick",
    "Quiet",
    "Rare",
    "Rugged",
    "Shiny",
    "Silly",
    "Strong",
    "Tall",
    "Trustworthy",
    "Ugly",
    "Unique",
    "Vibrant",
    "Wild",
    "Witty",
    "Young",
    "Zany",
    "Zealous"
];